### PR TITLE
Who uses Sass MQ?

### PR DESCRIPTION
**Pull request by kaelig**
Thanks to the awesome people who are using Sass MQ!

Feel free to add your company in the comments of this issue.

### CODE REVIEW

**Comment by RyanRoberts** [comment]
We use it at http://eqdesign.co.uk :+1:

**Comment by slavanga** [comment]
Are you only looking for companies?
I use Sass MQ in [Baseguide] (https://github.com/slavanga/baseguide).

**Comment by kaelig** [comment]
Thank you for using Sass MQ, Slavanga. I've added the project to the list.

**Comment by slavanga** [comment]
Cool, thank *you* for creating this fantastic mixin.

**Comment by mcaskill** [comment]
I use a [variant of Sass MQ](https://github.com/mcaskill/sass-mq) on personal projects. We also use the variant at [Locomotive](http://locomotive.ca/).

**Comment by jaicab** [comment]
We use it on every project at [Base Creative](http://www.basecreative.co.uk) :+1:

**Pull request merged**
