### PR TITLE
added eyeglass index.scss file to files list

### PR DESCRIPTION
**Pull request by PJL101**
addresses issue #71

### CODE REVIEW

**Comment by kaelig** [comment]
Thank you so much @PJL101, can you add Node 5 to the travis build configuration so that Travis runs tests in both environments (v0.12 and v5)?

**Comment by PJL101** [comment]
@kaelig is it worth adding 4 as well as it's the LTS release?

**Comment by kaelig** [comment]
Ha yeah, good point, thanks!

**Comment by PJL101** [comment]
Done!

**Comment by kaelig** [comment]
Many thanks, I'll bump the version in a few minutes.

**Pull request merged**
