### PR TITLE
Update/dart sass no ruby no node use of scoped modules

### PR DESCRIPTION
**Pull request by area73**
# Context

With the latest versions of sass , many features have been added or deprecated and  makes this library needed to be updated.

# Issues

Current Releases for sass engines are:
**Dart Sass 1.34.0**: Dart Sass is the primary implementation of Sass, which means it gets new features before any other implementation. Also currently is the only one maintain

**LibSass 3.6.5**: LibSass is Deprecated
please read https://sass-lang.com/blog/libsass-is-deprecated

**Ruby Sass ⚰**
Ruby Sass was the original implementation of Sass, but it reached its end of life as of 26 March 2019. It's no longer supported, and Ruby Sass users should migrate to another implementation.

This MR updates deprecations and removes some test for node-sass since is also deprecated and not compatible with the latest features of dart-sass

# Updates

* Updates descriptions of `@import` wihich are deprecated in favor of modules `@use` (https://sass-lang.com/documentation/at-rules/use)

* use of math.div instead of regular ` / ` since it is deprecated and it will be removed in `dart-sass 2.x`. (https://sass-lang.com/documentation/breaking-changes/slash-div)

### CODE REVIEW

**Comment by kaelig** [comment]
Thank you for looking into this!

I haven't had time to update my pr (https://github.com/sass-mq/sass-mq/pull/128), so this is very welcome.

It looks like there's more to it than simply updating how code is called. To avoid the headache of having to test multiple versions of Sass in CI and support both the legacy and the new module system**, let's drop support for all versions of Sass except Dart Sass**.

It means we'll probably have to change the way Sass MQ works in certain cases.

For example, does changing settings on the fly work, or do we need to provide an alternative?

https://github.com/sass-mq/sass-mq/blob/e653555abab7668f58ee0abb5714063249a0173e/test/_after-import.scss#L120-L123

**Comment by area73** [comment]
@kaelig , you are right I didn't pay attention to those vars. So to me I think there are two ways to solve this problem.

The first one will be to create separate files for each test alternative , so we could end up with something like:

`sass-mq/test/_after-import.scss` with default var values.

Another file: 

`sass-mq/test/_after-import-no-responsive-desktop.scss` 

With:
 ```scss
 $mq-responsive: false; 
 $mq-static-breakpoint: desktop; 
 ```

And so on:

`sass-mq/test/_after-import-no-responsive-no-print.scss` 

with:
```scss
/* Do not rasterize print media queries into when $mq-responsive is false */
$mq-responsive: false;
$mq-media-type: all;
```

So basically having a file for each use case were we need to change vars.

Also please note that we will probably **need to extract styles mixin** to a third file to be use in each use case

The second option will be to have all of them in the same file but then you will need to create named @use '../mq' for each override, and also do some extra work to reuse the styles mixin. 

Something like:

```scss
// sass-mq/test/_after-import.scss
@use '../mq';
@use '..mq' as mq-no-responsive-desktop with (
  $mq-responsive: false,
  $mq-static-breakpoint: desktop
);

@use '..mq' as no-responsive-no-print with (
  $mq-responsive: false,
  $mq-media-type: all
);
....
``` 

To me it makes more sense the first approach, but I'm open to any suggestion.
I can work on either solution over the weekend if you like. 
What do you think?

**Comment by kaelig** [comment]
Thank you, let's forget about "getting the tests to pass" for the sake of this discussion, and open the door to possibly redesigning the API to make the same kind of feature both possible and elegant.

If we can't make it elegant, I'm open to removing the feature rather than shoehorning all of Sass MQ into a different module paradigm.

I haven't use Sass modules in any production codebase yet so I'm open to suggestions!

**Comment by area73** [comment]
Yes I agree, I'm going to open an issue so we can discuss all these things there and try to see the best approach.

**Comment by joshdavenport** [comment]
In the meantime, it may worthwhile checking for the existence of `math.div` to maintain compatability between Dart Sass 1.x and 2.x. Something like:

```
@use "sass:meta"; // Include sass:meta to allow inspection of available sass features
@use "sass:math"; // Include sass:math so math.div is available
// See https://sass-lang.com/documentation/breaking-changes/slash-div

/// Check if math.div exists to assist with compatability between dart-sass versions
///
/// @example scss
///  @if mq-use-sass-math-for-division() {
///    $size: math.div($px, $base-font-size);
///  } @else {
///    $size: $px / $base-font-size;
///  }
///
/// @returns {bool}
@function mq-use-sass-math-for-division() {
  @return map-has-key(meta.module-functions("math"), "div");
}
```

Used as below, for example in the current `mq-px2em` function:

```
$size: null;
@if mq-use-sass-math-for-division() {
  $size: math.div($px, $base-font-size);
} @else {
  $size: $px / $base-font-size;
}
@return $size * 1em;
```

Perhaps it's overkill to try and support both when the library can just state it requires 2.x when that comes though.

**Comment by batmanhit** [comment]
This seems like a great PR to remove warnings. @area73 .
@kaelig , is there any plan to fix build issues and merge this. That would be great.
Cheers

**Comment by area73** [comment]
@batmanhit , I opened an issue to target this and other issues in more depths (https://github.com/sass-mq/sass-mq/issues/143).

My plan is to try to open a new PR by the end of the week with all the things that we state on that issue for @kaelig to take a look , since he is the owner of the library he may point us into one or other direction and see what he likes / dislikes about it

**Comment by area73** [comment]
ok so I finally upload the new PR, https://github.com/sass-mq/sass-mq/pull/144, for you to discuss.
At the moment I will close this MR since it is cover with the new one , and I will wait for @kaelig for his thoughts and possible next steps to be taken

**Pull request closed without merging**
