### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by harrinsonmb**
I think that it's going to be nice add this little explanation in the readme file or otherwise knowing this, is going to be a bit more difficult.

### CODE REVIEW

**Comment by kaelig** [comment]
Thanks for using sass-mq and for this contribution! Could you show a use case for this?

**Comment by harrinsonmb** [comment]
Of course! 

I have used it to do this. 

https://gist.github.com/harrinsonmb/12179997683ade8b8a7e442ac9593166

It's an iteration that sets some dynamic variables using dynamic queries.

**Comment by kaelig** [comment]
Thank you!

This is sort of documented in this documentation: http://sass-mq.github.io/sass-mq/#undefined-mixin-mq

Let me put an example in the README.

**Comment by kaelig** [comment]
@harrinsonmb I've just added some examples, let me know if this clarifies the matter: https://github.com/sass-mq/sass-mq/blob/master/README.md#verbose-and-shortand-notations

**Comment by harrinsonmb** [comment]
Oh nice!
From today I am going to start using that documentation. Thanks for care about our opinions!

**Comment by harrinsonmb** [comment]
@kaelig even better than expected, that's a perfect explanation, thank you so much for creating this useful plugin and thanks again for considering our opinions.

**Pull request closed without merging**
