### PR TITLE
Override px2em Tests

### PR DESCRIPTION
**Pull request by smbeiragh**
Tests for width-override.
using git diff for checking tests is not a good option, results depends on sass compilers and versions. for me your test fails because my compiler outputs no new line between each rule set. I only commit the new css file (test-width-override.css) and didn't commit test.css to prevent test failing on your system.
a better solution for testing should be developed.

Thank you.

### CODE REVIEW

**Comment by kaelig** [comment]
Thanks! Can you tell me more about the running environment (operating system, version of Sass…)? I'd like to understand why there's a difference between files.

Also: it's not ideal to use `git diff` to test but it's also the easiest way. There aren't really any good testing frameworks for Sass. I've been working on something, but it's not perfect either (and harder to maintain than a `git diff`). See https://github.com/Financial-Times/o-grid/tree/3e5148ca5cbea9a777db53d76d690f414b3b2205/test

**Comment by smbeiragh** [comment]
OS Ubuntu 14.0.4
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
Sass 3.4.18

node-sass output is identical

in addition to compile using locally installed node-sass in project, you need to change node-sass to node_modules/.bin/node-sass in test.sh

for testing, I don't know ruby. what I would suggest is comparing using [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) diff and nodejs for better integration with npm test command.

**Comment by kaelig** [comment]
Thanks! This line break business seems weird.

> in addition to compile using locally installed node-sass in project, you need to change node-sass to node_modules/.bin/node-sass in test.sh

Are you sure about this? Looks like travis handles this fine.

> for testing, I don't know ruby. what I would suggest is comparing using AST diff and nodejs for better integration with npm test command.

Yes that would be ideal but I'm not sure I want something that complex to maintain. See #69 for an improvement.

**Comment by smbeiragh** [comment]
> Are you sure about this? Looks like travis handles this fine.

I don't know. but when you run test.sh locally it will looks for global node-sass command and just can't find it and the sh file doesn't show command not fount message! if copy and paste the node-sass command in terminal the error 'command not found' appears. it seems sh is swallowing error. I have now idea travis how handles this.

**Comment by kaelig** [comment]
Thank you again @smbeiragh, I've merged your changes manually (see c46fab6).

**Pull request closed without merging**
